<?php

/** autogenerated file */


class Ragtek_ArrayDev_Config10 extends Ragtek_DeveloperTools_ConfigBase{

    protected $_jsFiles = array();
    protected $_styleFiles = array();


    CONST ADDON_ID = 'ragtekMM';

}
